### ISSUE TITLE
Add support for PromethION

### ISSUE THREAD

**Issue by davidebolo1993** [davidebolo1993/NanoR#12]
It would be nice to add support for PromethION sequencing data. Is there any PromethION-user that can share a subset from this platform so that I can check how feasible would be to implement PromethION support in NanoR?

**Comment by hernandezvargash** [comment]
Hi @davidebolo1993 , 
Thanks for building this package.
This is an old issue, but if you are still interested I'd be happy to share some PromethION data.
Best,
H

**Comment by davidebolo1993** [comment]
Hi @hernandezvargash,

sure, go ahead. This issue is still open because I could not find a proper dataset for testing. I'm also interested in the channels/muxes distribution in PromethION flow cells, so that I can try to implement some sort of activity heatmaps similar to those generated by NanoR for MinION/GridION platforms. Have find nothing though. Do you have any information about the physical distribution of channels and muxes in PromethION flow cells ?
Thanks,

Davide

**Comment by matryoskina** [comment]
Hi Davide, are you still interested in some PromethION data?
I am trying to use your package with PromethION data for my manuscript, but I'm not sure it will work if there is no testing on it.

**Comment by davidebolo1993** [comment]
Hi @matryoskina,

In principle, the only functions that should be adjusted to make NanoR working with PromethION data are those used for plotting channels and muxes' activity in NanoStats(NanoStatsM and G). This should be doable, but I need to know the exact disposition of channels and muxes in a PromethION flow cell. Any references on this ?
