### ISSUE TITLE
I cannot install NanoR package

### ISSUE THREAD

**Issue by Tschubaty** [davidebolo1993/NanoR#13]
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

#installation prerequisites 

ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE, repos="http://cran.cnr.berkeley.edu/")
  sapply(pkg, require, character.only = TRUE)
}
packages <- c("ggplot2","reshape2","RColorBrewer","scales","gridExtra")
ipak(packages)
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
packages<-c('rhdf5', 'ShortRead')
BiocManager::install(packages)

> 
>       ggplot2     reshape2 RColorBrewer       scales    gridExtra 
>          TRUE         TRUE         TRUE         TRUE         TRUE 
> 
>  package ‘rhdf5’ successfully unpacked and MD5 sums checked
>  package ‘ShortRead’ successfully unpacked and MD5 sums checked
> 
> 

**install.packages('C:/Users/owner/Documents/GitHub/NanoR.tar.gz', repos=NULL)**

> Installing package into ‘C:/Users/owner/Documents/R/win-library/3.6’
> (as ‘lib’ is unspecified)
> Warning: invalid package 'C:/Users/owner/Documents/GitHub/NanoR.tar.gz'
> Error: ERROR: no packages specified
> Warning in install.packages :
>   installation of package ‘C:/Users/owner/Documents/GitHub/NanoR.tar.gz’ had non-zero exit status
### 
What am I missing here, that it does not get installed?

**Comment by davidebolo1993** [comment]
Hi @Tschubaty.

Thanks for getting in touch. From the path you specified ('C:/Users/owner/Documents/GitHub/NanoR.tar.gz', repos=NULL) it seems to me that you are a Windows user. Generally speaking, Windows users have to replace all "/" with "\\". This is true for all the paths you specify within the R environment. 

For your example

'C:/Users/owner/Documents/GitHub/NanoR.tar.gz'

The correct path should be:

'C:\\Users\\owner\\Documents\\GitHub\\NanoR.tar.gz'

This will probably solve your problem.

**Comment by Tschubaty** [comment]
Thx, the file string path was the problem.
install.packages("C:/Users/owner/Documents/GitHub/NanoR/NanoR.tar.gz", repos=NULL) worked
