### ISSUE TITLE
sequencing_summary.txt does not work with NanoPrepareM

### ISSUE THREAD

**Issue by martinhaagmans** [davidebolo1993/NanoR#14]
Hi,

when I run NanoPrepareM with a sequencing summary and fastq_pass as explained here: https://davidebolo1993.github.io/nanordoc/usage/usage.html#data-analysis-and-visualization it gives 
```
Error in NanoPrepareM(DataSummary = summary, DataFastq = fastq) : 
  unused arguments (DataSummary = summary, DataFastq = fastq)

```

NanoPrepareG does work.

Cheers,
Martin

**Comment by davidebolo1993** [comment]
Hi @martinhaagmans,

this is indeed a typo in the documentation. Just fixed this.

https://davidebolo1993.github.io/nanordoc/usage/usage.html#data-analysis-and-visualization

Thanks !

Davide
