### ISSUE TITLE
Link for data download

### ISSUE THREAD

**Issue by HPiyadasa** [davidebolo1993/NanoR#15]
Hi,

I was wondering if I could get an updated link to download the dataset from the paper? I am learning how to analyze data from a Nanopore Seq and would like to experiment with your dataset! 

Thanks!
Hadeesha

**Comment by davidebolo1993** [comment]
Hi @HPiyadasa,

The links from both the paper and the previous discussions expired a while ago. Still, you can use data from Nanopolish (https://nanopolish.readthedocs.io/en/latest/quickstart_call_methylation.html) to test NanoR. Simply download and untar the dataset before using the tool. Just let me know if you need further help with your tests. 

Best,

Davide

**Comment by HPiyadasa** [comment]
Hi Davide, 

Thanks for the info! appreciate it. 

Best, 
Hadeesha
