### ISSUE TITLE
installation issue with NanoR

### ISSUE THREAD

**Issue by saumitra14** [davidebolo1993/NanoR#16]
Hello,

I have been getting the following message during installation of NanoR. Could you please help me with this?
"installation of package ‘/path/to/NanoR/NanoR.tar.gz’ had non-zero exit status"

**Comment by davidebolo1993** [comment]
Hi @saumitra14,

you should replace ‘/path/to/NanoR/NanoR.tar.gz’ with the local path to your NanoR.tar.gz file. This should work.

**Comment by saumitra14** [comment]
Thanks!!
it worked.

**Comment by saumitra14** [comment]
How do I launch and run "Datasummary" and  "DataFastq" functions when I am trying to run NanoPrepareG
I am getting the following message.
"could not find function "DataSummary"

**Comment by davidebolo1993** [comment]
Hi @saumitra14,

DataSummary and DataFastq are not functions. They are variables instead, and must contain your local path to the sequencing summary file and fastq directory generated by your sequencing run. The documentation (https://davidebolo1993.github.io/nanordoc/usage/usage.html#data-analysis-and-visualization) should help you with all the questions on how to run NanoR, feel free to re-open if you get into a real issue.
Please note that GitHub issues are mostly intended to help with bugs/questions that are related to a specific tool (NanoR, in this case) and this usually does not include explaining the basis of a programming language. 
Hope this helps, BTW.

Best,

Davide

**Comment by saumitra14** [comment]
Thanks a lot.
    On Friday, October 16, 2020, 11:30:21 AM GMT+5:30, Davide Bolognini <notifications@github.com> wrote:  
 
 


Hi @saumitra14,

DataSummary and DataFastq are not functions. They are variables instead, and must contain your local path to the sequencing summary file and fastq directory generated by your sequencing run. The documentation (https://davidebolo1993.github.io/nanordoc/usage/usage.html#data-analysis-and-visualization) should help you with all the questions on how to run NanoR, feel free to re-open if you get into a real issue.
Please note that GitHub issues are mostly intended to help with bugs/questions that are related to a specific tool (NanoR, in this case) and this usually does not include explaining the basis of a programming language.
Hope this helps, BTW.

Best,

Davide
