### ISSUE TITLE
Issue Downloading R 

### ISSUE THREAD

**Issue by daveyrobeck** [davidebolo1993/NanoR#17]
Warning in install.packages :
  package ‘C:\Users\davey\Downloads\NanoR.tar.gz’ is not available for this version of R

Currently Running R 4.0.2 or 4.0.3 and I get the same error regardless of which one I use. 
What is the latest version of R that is compatible with NanoR
It also claims that it is incompatible with 3.6.3

**Comment by davidebolo1993** [comment]
Hi @daveyrobeck,

I don't think this is an issue with the R version. Did you specifify "repos=NULL" while installing with install.packages?

**Comment by davidebolo1993** [comment]
Any updates on this?
