### ISSUE TITLE
Error using NanoR H5Fopen

### ISSUE THREAD

**Issue by phrh** [davidebolo1993/NanoR#19]
Hi,
I have four data sets. For two NanoR works fine but for the other two I am getting this error. Do you have any idea what could it be?

Error in H5Fopen(First) : HDF5. File accessibilty. Unable to open file.
Calls: NanoPrepareM -> H5Fopen

Looking forward for an answer

**Comment by davidebolo1993** [comment]
Hi @phrh,

this is indeed an accessibility error. I don't know what your command line look-like but, knowing the code of NanoPrepareM, the H5Fopen function is called when it comes to open the first (and the last) multi-read failed/skipped FAST5 files to count how many reads are in these files. I never got into this error, but it seems to me that this can happen either when no failed/skipped FAST5 are found in the directory provided to DataFail/DataSkip or if you do not have read/write permissions on those files. If there are no available failed/skipped FAST5 for those 2 datasets, do not specify any DataFail/DataSkip folder. 
Hope this helps,

Davide

**Comment by phrh** [comment]
yes thank you. You are right 0 files in the skipped folder. Thanks again!
