### ISSUE TITLE
NanoStatsM & NanoPrepareG error

### ISSUE THREAD

**Issue by IsabelFE** [davidebolo1993/NanoR#23]
Hello I am new to NanoR and I am getting an error in NanoStatsM

```
NanoStatsM(NanoMList=Mlist, NanoMTable=Mtable, DataOut=output, KeepGGObj = FALSE)

Error in file(file, ifelse(append, "a", "w")) : cannot open the connection
```

It generates Activity, LvsQ, PFGC, RBLQ and Yield pdfs. Should I be getting any extra output?

Thanks

**Comment by IsabelFE** [comment]
I am getting the same issue with NanoPrepareG.

Looking at the code:

```
#' @return Plots: \cr 
#' - Yield.pdf (accumulation of reads and bps); \cr 
#' - RBLQ.pdf (# reads, # bps, length and quality overview every 30 minutes of experiment); \cr 
#' - LvQ.pdf (length and quality compared jointly); \cr 
#' - PFGC.pdf (passed and failed reads, GC content if computed); \cr 
#' - Activity.pdf (channels and muxes activity (# bps). Inactive channels and muxes are grey-colored) \cr
#' Table: \cr
#' - summary.txt (table with major statistics for the sequencing run)
```

I can see that I am missing the summary.txt table.

Also I am not getting the DataForComparison folder

**Comment by davidebolo1993** [comment]
Hi @IsabelFE,

that's really hard to say what's going on here without having a reproducible example. Can you share your data? Also, It would be nice to know how you are running NanoStatsM and NanoStatsG. 

Thanks,

Davide

**Comment by IsabelFE** [comment]
Hi Davide,

I am running the examples as you indicate in https://davidebolo1993.github.io/nanordoc/usage/usage.html#data-analysis-and-visualization.

I have a folder "20210511_1804_MN36832_AGR387_63fbbe5b" with the output of my Nanopore run. I wasn't sure about the difference between the 2 workflows, so I tried both:

```{r}
sequencing_run<-"20210511_1804_MN36832_AGR387_63fbbe5b"
pass<-file.path(sequencing_run,"fast5_pass")
fail<-file.path(sequencing_run,"fast5_fail")
skip<-file.path(sequencing_run,"fast5_skip")
output<-file.path("NanoR_FAST5/20210511_1804_MN36832_AGR387_63fbbe5b")

Mlist<-NanoPrepareM(DataPass=pass,DataFail=fail,DataSkip=skip, MultiRead=TRUE)
Mtable<-NanoTableM(NanoMList=Mlist, DataOut=output, Cores=6, GCC=FALSE)
NanoStatsM(NanoMList=Mlist, NanoMTable=Mtable, DataOut=output, KeepGGObj = FALSE) 
```

```{r}
sequencing_run<-"20210511_1804_MN36832_AGR387_63fbbe5b"
summary<-file.path(sequencing_run,"sequencing_summary_AGR387_17aa163f.txt")
fastq<-file.path(sequencing_run, "fastq_pass")
output<-file.path("NanoR_FASTQ/20210511_1804_MN36832_AGR387_63fbbe5b")

Glist<-NanoPrepareG(DataSummary=summary,DataFastq=fastq)
Gtable<-NanoTableG(NanoGList=Glist, DataOut=output, GCC=TRUE) 
NanoStatsG(NanoGList=Glist, NanoGTable=Gtable, DataOut=output, KeepGGObj = FALSE) 
```

**Comment by IsabelFE** [comment]
I can share the folder in GoogleDrive with your email listed in GitHub: davidebolognini7@gmail.com if that is helpful

**Comment by davidebolo1993** [comment]
Hi @IsabelFE,

I'll have a look next monday and let you know.

Best,

Davide

**Comment by IsabelFE** [comment]
Thanks!

**Comment by davidebolo1993** [comment]
Hi @IsabelFE,

I just had a quick look at your data and those are barcoded data. For the time being, NanoR does not deal with barcoded experiments. I will release a new version, ideally within one month, that should also handle barcoded runs.
In the meantime, you can generate an overview of the entire sequencing run by doing something like:

```R
output<-file.path("/path/to/output")
summary<-file.path("/path/to/sequencing_summary.txt")
fastq<-file.path("/path/to/fastq_pass/barcode01") #this is ignored because we set GCC to FALSE

List<-NanoPrepareG(summary, fastq)
Table<-NanoTableG(List,output,GCC=FALSE)
NanoStatsG(List,Table,output)
```

You should get few warnings, but all the output files are actually generated.
