### ISSUE TITLE
Renaming of MinKNOW files

### ISSUE THREAD

**Issue by ultrav71** [davidebolo1993/NanoR#24]
When using GRIDIon, a sample manifest is created, and MinKNOW files are assigned filenames per their barcodes. I am aware that this manifest must be created manually, however I am wondering if there is a way to automatically get the filenames to revert to their corresponding sample names afterwards?

**Comment by davidebolo1993** [comment]
Hi @ultrav71,

thanks for getting in touch. Can you share an example with additional details on what you need?

Thanks,

Davide

**Comment by ultrav71** [comment]
Hi Davide,

Thank you for getting back to me so quickly.

I work with a group that processes large volumes of Covid testing and
reports those data to several government bodies who want the files in
specific formats, i.e., the actual sample names.

24 samples are run on 5 flow cells through a GRIDIon using NextFlow and
MinKNOW, and are processed in an Ubuntu environment. When the samples are
processed by the MinKNOW sw, they are assigned filenames based on their bar
codes.

After sequencing, the files must then be manually changed to reflect the
actual samples before they are sent out to various health organizations. I
have been asked to help find a way to automate this renaming process as it
is quite time-consuming, but I am quite lost and am not sure this is
possible.

Any insight you could provide would be greatly appreciated.

Kindest regards,
Tanya


Tanya E. Kelly, Ph.D.
Trinity College Dublin




"The greatest value of a picture is when it forces us to notice what we
never expected to see. "
- John Tukey

*Emails are typically seen and replied to between 9 a.m. and 6 p.m. Monday
through Friday.*

**Comment by davidebolo1993** [comment]
I think this is indeed possible, but I need an example dataset and the expected output to see if I can quickly implement what you are asking into NanoR.

Thanks,

Davide

**Comment by ultrav71** [comment]
Hi Davide,

That is fantastic! I will try to get you the sample dataset asap. I would
like to connect you with my colleagues directly, if that is okay with you?

Tanya

Tanya E. Kelly, Ph.D.
Trinity College Dublin



"The greatest value of a picture is when it forces us to notice what we
never expected to see. "
- John Tukey

*Emails are typically seen and replied to between 9 a.m. and 6 p.m. Monday
through Friday.*

**Comment by davidebolo1993** [comment]
Sure, go ahead

Davide

**Comment by ultrav71** [comment]
Hi everyone,

I am copying everyone into this email for the purpose of introducing
Davide. Davide is a github member and a NanoR developer and I think he can
do what you are asking with regards to automatically renaming sequence
files.

What he would like is an example of the dataset along with expected output
to see if he can incorporate that into NanoR.

Can that be sent to him? Or to me and I will pass it along?

Thanks,
Tanya


Tanya E. Kelly, Ph.D.
Trinity College Dublin


"The greatest value of a picture is when it forces us to notice what we
never expected to see. "
- John Tukey

*Emails are typically seen and replied to between 9 a.m. and 6 p.m. Monday
through Friday.*

**Comment by ultrav71** [comment]
Hi Davide,

We are running the nextflow wf-artic workflow. We get out primer trimmed bam files and an allconsensus.fasta file with the fasta of 24 samples. PHE want us to rename this Sample_name.Run_name.bam and Sample_name.Run_name.fasta for each sample. Which we are doing manually now, takes too long and not exactly accurate way to do it! I have attached a screenshot of the output folder

They have also asked for non primer trimmed bam files but as this is the output of the workflow not sure how to change this.

Thanks,


Sara Temelso
NGS Scientist
Eurofins County Pathology Ltd
8 Huxley Road
Surrey Research Park
Guildford
Surrey
GU2 7RE
Tel: +447501805142
email: ***@***.******@***.***>

***@***.***

**Comment by davidebolo1993** [comment]
Hi all, 

this is not something related to NanoR, so I'm about to close this issue. We can of course discuss about what you need, but let's do this by email (davidebolognini7@gmail.com - send me a new mail). Just for your information, I can't really see any attachment in your email.

Best,

Davide
