### ISSUE TITLE
Reformat repository format to be devtools::install_github() compliant?

### ISSUE THREAD

**Issue by Shians** [davidebolo1993/NanoR#3]
If you re-organise your repository to be simply the folder containing the R package. i.e. the contents of decompressing NanoR.tar.gz then you can allow users to install directly off Github with all specified dependencies. See ["benefits of using github"](http://r-pkgs.had.co.nz/git.html#github-benefit), a minimal example of how such repositories look [here](https://github.com/hadley/mylittlepony). You can add Github `README` image assets like to some folder like `gh_assets` and then add it to `.Rbuildignore` so that it does not get built into your package.

The result of doing is will be that people can write

```
devtools::install_github("davidebolo1993/NanoR")
```

and have your package installed with all its stated dependencies.

**Comment by davidebolo1993** [comment]
HI @Shians, thank You for your suggestion !

Of course is something to consider. For the moment, I want to leave the repository as it is: NanoR has been submitted to a scientific journal and I want the Reviewer to find all as it is described in the article. But of course it would be easier for users to install directly from within R even if I prefer dependecies to be installed separetly, as someone may need different versions of the packages depending on the R version he runs.

Thank You again !
