### ISSUE TITLE
Can not download sample data set 

### ISSUE THREAD

**Issue by henganl2** [davidebolo1993/NanoR#7]
Hi, 
I was trying to download the sample dataset from the link provided from the paper, 
but that link showed an error as below: 

"Not Found
The server encountered a problem while trying to process your request. This may be due to insufficient permissions, a configuration problem, network interruption, bug or hardware failure."

Is this link out of date? 

Thanks!! I really like this package and want to try it for my data analysis. 

Best, 
Heng-An

**Comment by davidebolo1993** [comment]
Hi @henganl2 !

The link is mantained by EMBL GeneCore facility. I'm not at EMBL at the moment, but I'll be back in a week; meanwhile, I'll check with guys from IT what happened with the link. Thanks for getting in touch and appreciating the package.

Best,

Davide

**Comment by henganl2** [comment]
Thanks so much!

**Comment by davidebolo1993** [comment]
Hi @henganl2 


new link :
https://faspex.embl.de/aspera/faspex/external_deliveries/823?passcode=c4aa66d379850be32163f8517fa04750aec7a3bf&expiration=MjAxOS0wNS0wMlQwNjo1Nzo0MFo=


I guess this is not a stable solution but may work for the moment.


Best

**Comment by henganl2** [comment]
Hi Davide, 

I got the sample data. Thanks again :) 

Best, 
Heng-An

**Comment by HPiyadasa** [comment]
Hi, Could I also get a link to download the dataset. The link from faspex is expired. Thanks!
