### ISSUE TITLE
I cannot install NanoR package

### ISSUE THREAD

**Issue by Matteo1988** [davidebolo1993/NanoR#8]
Hi after the download of NanoR (git clone https://github.com/davidebolo1993/NanoR.git), when I launch the command:

install.packages("/home/matteo/NanoR/NanoR.tar.gz", repos=NULL)

I have this error:
Installing package into ‘/home/matteo/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
ERROR: dependency ‘ShortRead’ is not available for package ‘NanoR’
* removing ‘/home/matteo/R/x86_64-pc-linux-gnu-library/3.3/NanoR’
Warning in install.packages :
  installation of package ‘/home/matteo/NanoR/NanoR.tar.gz’ had non-zero exit status

I made some mistakes?

**Comment by davidebolo1993** [comment]
Hi @Matteo1988 


Yes, You're missing the ShortRead package, as the report says. 
As writte in the README of the repository, in addition to the packages you can get from CRAN, you have to install some bioconductor packages, namely rhdf5 and ShortRead. This can be achieved using:

source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5",suppressUpdates=TRUE, suppressAutoUpdate=TRUE)
biocLite("ShortRead",suppressUpdates=TRUE, suppressAutoUpdate=TRUE)



Let me know if You need something else !

Cheers

**Comment by Matteo1988** [comment]
Sorry! I was sure that I did, but cleary I miss that command. Sorry again, and thank you very much
